services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source
    ports:
      - 5434:5432
    volumes:
      - db-source-data:/var/lib/postgresql/data

volumes:
  db-source-data:
