services:
  db-dev:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source
    ports:
      - 5434:5432
    volumes:
      - db-source-data:/var/lib/postgresql/data

  db-test:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source-test
    ports:
      - 5435:5432
    volumes:
      - db-source-test-data:/var/lib/postgresql/data

volumes:
  db-source-data:
  db-source-test-data:
